//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: pongcs_rpc_messages.proto
// Note: requires additional types generated from: funapi/distribution/fun_rpc_message.proto
namespace Pongcs
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EchoRpcMessage")]
  public partial class EchoRpcMessage : global::ProtoBuf.IExtensible
  {
    public EchoRpcMessage() {}
    
    private string _message;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string message
    {
      get { return _message?? ""; }
      set { _message = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool messageSpecified
    {
      get { return this._message != null; }
      set { if (value == (this._message== null)) this._message = value ? this.message : (string)null; }
    }
    private bool ShouldSerializemessage() { return messageSpecified; }
    private void Resetmessage() { messageSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
// Generated from: pongcs_messages.proto
// Note: requires additional types generated from: funapi/network/fun_message.proto
// Note: requires additional types generated from: funapi/service/multicast_message.proto
namespace Pongcs
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PbufEchoMessage")]
  public partial class PbufEchoMessage : global::ProtoBuf.IExtensible
  {
    public PbufEchoMessage() {}
    
    private string _msg;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string msg
    {
      get { return _msg; }
      set { _msg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PbufAnotherMessage")]
  public partial class PbufAnotherMessage : global::ProtoBuf.IExtensible
  {
    public PbufAnotherMessage() {}
    
    private string _msg;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string msg
    {
      get { return _msg?? ""; }
      set { _msg = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool msgSpecified
    {
      get { return this._msg != null; }
      set { if (value == (this._msg== null)) this._msg = value ? this.msg : (string)null; }
    }
    private bool ShouldSerializemsg() { return msgSpecified; }
    private void Resetmsg() { msgSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PbufHelloMessage")]
  public partial class PbufHelloMessage : global::ProtoBuf.IExtensible
  {
    public PbufHelloMessage() {}
    
    private string _message;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string message
    {
      get { return _message?? ""; }
      set { _message = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool messageSpecified
    {
      get { return this._message != null; }
      set { if (value == (this._message== null)) this._message = value ? this.message : (string)null; }
    }
    private bool ShouldSerializemessage() { return messageSpecified; }
    private void Resetmessage() { messageSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}